### ISSUE TITLE
spiflash File type fixed

### ISSUE THREAD

**Issue by ladyada** [MrBryonMiller/DOS-for-Adafruit-M4-Express-boards#1]
try the latest release of our SPIFlash library - the File type collision should bfixed!

**Comment by MrBryonMiller** [comment]
Problem is I don't know how to use it.  In this tiny test program I tried the following.  I'm able to define a SD File but on the next line I'm trying to define the fatfs File and it is not correct. I don't know how to make it right.

```
#include <SD.h>
#include <Adafruit_SPIFlash_FatFs.h>
void setup() {
SDFile     bmpFile;
Adafruit_SPIFlash_FatFs::File bmpFlashFile = fatfs.open("adabot.bmp");
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

**Comment by MrBryonMiller** [comment]
Figured it out. Thanks!
